/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prova;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author laboratorio
 */
public class FormularioBiblioteca extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormularioBiblioteca.class.getName());
    
    private Arquivo arquivo;
    private javax.swing.table.DefaultTableModel modeloTabela;
    private int indexSelecionado = -1;
    
    public FormularioBiblioteca() {
        initComponents();
        
        arquivo = new Arquivo("Livros");
        
        String[] colunas = {"Titulo", "Autor", "Ano publicacao", "Tipo", "Categorias",
        "Situacao do Livro"};

        modeloTabela = new javax.swing.table.DefaultTableModel(colunas, 0);
        tblLivros.setModel(modeloTabela);

        carregarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNome = new javax.swing.JLabel();
        lblAutor = new javax.swing.JLabel();
        lblAnoPublicacao = new javax.swing.JLabel();
        lblSituacaoLivro = new javax.swing.JLabel();
        lblCategoria = new javax.swing.JLabel();
        lblEscolha = new javax.swing.JLabel();
        rdo_Fisico = new javax.swing.JRadioButton();
        rdo_Digital = new javax.swing.JRadioButton();
        txtTitulo = new javax.swing.JTextField();
        txtAutor = new javax.swing.JTextField();
        txtAnoPublicacao = new javax.swing.JTextField();
        cmdCategoria = new javax.swing.JComboBox<>();
        rdb_NaoIniciada = new javax.swing.JRadioButton();
        rdb_EmAndamento = new javax.swing.JRadioButton();
        rdb_Concluida = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLivros = new javax.swing.JTable();
        btnCadastrar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNome.setText("Titulo");

        lblAutor.setText("Autor");

        lblAnoPublicacao.setText("Ano Publicacao");

        lblSituacaoLivro.setText("Situacao do Livro");

        lblCategoria.setText("Categoria");

        lblEscolha.setText("Qual tipo de livro deseja inserir?");

        rdo_Fisico.setText("Fisico");
        rdo_Fisico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_FisicoActionPerformed(evt);
            }
        });

        rdo_Digital.setText("Digital");
        rdo_Digital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_DigitalActionPerformed(evt);
            }
        });

        txtTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloActionPerformed(evt);
            }
        });

        txtAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAutorActionPerformed(evt);
            }
        });

        cmdCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Tecnologia", "Ficcao", "Romance", "Historia" }));
        cmdCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCategoriaActionPerformed(evt);
            }
        });

        rdb_NaoIniciada.setText("Nao iniciada");
        rdb_NaoIniciada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb_NaoIniciadaActionPerformed(evt);
            }
        });

        rdb_EmAndamento.setText("Em endamento");

        rdb_Concluida.setText("Concluida");

        tblLivros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Titulo", "Autor", "Ano Publicacao", "Tipo do Livro", "Categoria do livro", "Situacao do livro"
            }
        ));
        jScrollPane1.setViewportView(tblLivros);

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCadastrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditar)
                .addGap(83, 83, 83))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblEscolha)
                        .addGap(18, 18, 18)
                        .addComponent(rdo_Fisico)
                        .addGap(18, 18, 18)
                        .addComponent(rdo_Digital))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblAnoPublicacao)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtAnoPublicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCategoria)
                                        .addGap(18, 18, 18)
                                        .addComponent(cmdCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblSituacaoLivro)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rdb_NaoIniciada)
                                        .addGap(18, 18, 18)
                                        .addComponent(rdb_EmAndamento)
                                        .addGap(18, 18, 18)
                                        .addComponent(rdb_Concluida))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblAutor)
                                    .addComponent(lblNome))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                    .addComponent(txtAutor)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEscolha)
                    .addComponent(rdo_Fisico)
                    .addComponent(rdo_Digital))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAutor)
                    .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnoPublicacao)
                    .addComponent(txtAnoPublicacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSituacaoLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdb_NaoIniciada)
                    .addComponent(rdb_EmAndamento)
                    .addComponent(rdb_Concluida))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar)
                    .addComponent(btnEditar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdo_FisicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_FisicoActionPerformed

    }//GEN-LAST:event_rdo_FisicoActionPerformed

    private void rdo_DigitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_DigitalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdo_DigitalActionPerformed

    private void txtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloActionPerformed

    private void txtAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAutorActionPerformed

    private void rdb_NaoIniciadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_NaoIniciadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdb_NaoIniciadaActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        String TipoLivro = null;
        String Titulo = txtTitulo.getText().trim();
        String Autor = txtAutor.getText().trim();
        
        if (rdo_Fisico.isSelected()) {
            TipoLivro = "Fisico";
     }  else if (rdo_Digital.isSelected()) {
            TipoLivro = "Digital";
        }
        
        String AnoPubli = txtAnoPublicacao.getText().trim();
        String Categoria = (String) cmdCategoria.getSelectedItem();
        String SituacaoLivro = null;
        
        
        Livro livros = new Livro(Titulo,Autor,AnoPubli,TipoLivro,Categoria,SituacaoLivro);

        if (indexSelecionado == -1) {
            arquivo.adicionarLivro(livros);
            JOptionPane.showMessageDialog(null, "Livro cadastrado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
    }   else {
            arquivo.atualizarLivro(indexSelecionado, livros);
            JOptionPane.showMessageDialog(null, "Aluno atualizado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            indexSelecionado = -1;
    }
        
        arquivo.gravarAquivo();
        carregarTabela();
        limparCampos();    
    }
        
        private void carregarTabela() {
        modeloTabela.setRowCount(0);

        for (Livro a : arquivo.lerArquivo()) {
        modeloTabela.addRow(new Object[]{
            a.getTitulo(), a.getAutor(), a.getAnoPubli(), a.getCategoria(),
            a.getSituacaoLivro()
        });
    }
        for (Livro a : arquivo.lerArquivo()) {
        modeloTabela.addRow(new Object[]{
            a.getAutor(), a.getAnoPubli(), a.getTipoLivro(), a.getCategoria(),
            a.getSituacaoLivro()
        });
    }
        
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void cmdCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdCategoriaActionPerformed

    private void limparCampos() {
        txtTitulo.setText("");
        txtAutor.setText("");
        txtAnoPublicacao.setText("");
        lblEscolha.setText("");
        cmdCategoria.setSelectedIndex(0);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormularioBiblioteca().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JComboBox<String> cmdCategoria;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAnoPublicacao;
    private javax.swing.JLabel lblAutor;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblEscolha;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSituacaoLivro;
    private javax.swing.JRadioButton rdb_Concluida;
    private javax.swing.JRadioButton rdb_EmAndamento;
    private javax.swing.JRadioButton rdb_NaoIniciada;
    private javax.swing.JRadioButton rdo_Digital;
    private javax.swing.JRadioButton rdo_Fisico;
    private javax.swing.JTable tblLivros;
    private javax.swing.JTextField txtAnoPublicacao;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
